#
# Apache v2 license
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
#test-line
services:
  broker:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt_broker
    volumes:
      - ../utils/mosquitto:/mosquitto/config
    ports:
      - "1883:1883"
    networks:
      - app_network

  dlstreamer-pipeline-server:
    image: ${DLSTREAMER_PIPELINE_SERVER_IMAGE}
    hostname: dlstreamer-pipeline-server
    container_name: dlstreamer-pipeline-server
    read_only: true
    security_opt:
      - no-new-privileges
    build:
      context: ..
      target: dlstreamer-pipeline-server
      dockerfile: ${DLSTREAMER_PIPELINE_SERVER_DOCKERFILE}
      args:
        MSGBUS_LIB_VERSION: 4.0.0
        UTILS_LIB_VERSION: 4.0.0
        UID: ${UID}
        USER: ${PIPELINE_SERVER_USER}
        BASE_IMAGE: ${BASE_IMAGE}
        CMAKE_INSTALL_PREFIX: "/opt/intel/eii"
        # Download sources for GPL/LGPL/AGPL binary distributed components (yes/no)
        DOWNLOAD_GPL_SOURCES: "no"
        no_proxy: ${no_proxy}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    privileged: false
    tty: true
    entrypoint: ["./run.sh"]
    ports:
      - '8080:8080'
      - '8554:8554'
    networks:
      - app_network
    environment:
      - S3_STORAGE_HOST=${S3_STORAGE_HOST}
      - S3_STORAGE_PORT=${S3_STORAGE_PORT}
      - S3_STORAGE_USER=${S3_STORAGE_USER}
      - S3_STORAGE_PASS=${S3_STORAGE_PASS}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - ENABLE_RTSP=true
      - RTSP_PORT=8554
      - ENABLE_WEBRTC=true
      - WEBRTC_SIGNALING_SERVER=http://${WHIP_SERVER_IP}:${WHIP_SERVER_PORT}
      - no_proxy=$no_proxy,multimodal-data-visualization-streaming,${RTSP_CAMERA_IP},${OTEL_COLLECTOR_HOST},${S3_STORAGE_HOST}
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - RUN_MODE=EVA
      - GENICAM=Balluff
      - GST_DEBUG=1,gencamsrc:2
      - LOG_LEVEL=${LOG_LEVEL}
      # Default Detection and Classification Device
      - DETECTION_DEVICE=CPU
      - CLASSIFICATION_DEVICE=CPU
      - ADD_UTCTIME_TO_METADATA=true
      - RUNTIME_LICENSE_CHECK_FREQ_SECS=${RUNTIME_LICENSE_CHECK_FREQ_SECS}
      - APPLICATION_RESTART_FREQ_SECS=${APPLICATION_RESTART_FREQ_SECS}
      - HTTPS=false # Make it "true" to enable SSL/TLS secure mode, mount the generated certificates
      - MTLS_VERIFICATION=false # if HTTPS=true, enable/disable client certificate verification for mTLS
      # Model Registry Microservice
      - MR_VERIFY_CERT=${MR_VERIFY_CERT}
      # Append pipeline name to a publisher topic
      - APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC=false
      - REST_SERVER_PORT=8080
      - SERVICE_NAME=dlstreamer-pipeline-server
      - OPCUA_SERVER_IP=$OPCUA_SERVER_IP
      - OPCUA_SERVER_PORT=$OPCUA_SERVER_PORT
      - OPCUA_SERVER_USERNAME=$OPCUA_SERVER_USERNAME
      - OPCUA_SERVER_PASSWORD=$OPCUA_SERVER_PASSWORD
      - ENABLE_OPEN_TELEMETRY=${ENABLE_OPEN_TELEMETRY}
      - OTEL_COLLECTOR_HOST=${OTEL_COLLECTOR_HOST}
      - OTEL_COLLECTOR_PORT=${OTEL_COLLECTOR_PORT}
      - OTEL_EXPORT_INTERVAL_MILLIS=${OTEL_EXPORT_INTERVAL_MILLIS}
    volumes:
      # - "../resources:/home/pipeline-server/resources/"
      # - "../configs/default/config.json:/home/pipeline-server/config.json"
      - vol_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
      - "../certificates:/MqttCerts:ro"
      - "../Certificates/ssl_server/:/run/secrets/DLStreamerPipelineServer_Server:ro"
      - "../Certificates/model_registry/:/run/secrets/ModelRegistry_Server:ro"
      #  - "../user_scripts/udfs/python:/home/pipeline-server/udfs/python"
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "./mr_models:/home/pipeline-server/mr_models:rw"
    group_add:
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
      # render group ID for ubuntu 24.04 host OS
      - "992"
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # Selective rules can be applied for deployment
      - 'c 189:* rmw'
      - 'c 209:* rmw'
      - 'a 189:* rwm'
    devices:
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # USB camera devices
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "/dev:/dev"

networks:
  app_network:
    driver: bridge

volumes:
  vol_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
