name: "[DLSPS] Build helm charts weekly "
run-name: "[DLSPS]Build helm charts weekly"
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag'
        required: true
        type: string
      action-type:
        description: 'Choose if this run is weekly build or cache update'
        required: true
        type: choice
        options:
          - 'weekly'
          - 'cache'
permissions: {}
jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      with:
        persist-credentials: false
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.15.2  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #3.10.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package Helm Chart
      run: |
        cd edge-ai-libraries-repo/microservices/dlstreamer-pipeline-server/helm  
        helm package . --version ${{ inputs.image-tag }} --app-version ${{ inputs.image-tag }}
    - name: Push to GHCR
      run: |
        CHART_PACKAGE=$(ls edge-ai-libraries-repo/microservices/dlstreamer-pipeline-server/helm/dlstreamer-pipeline-server-3.1.0-helm.tgz)
        helm push $CHART_PACKAGE oci://ghcr.io/${{ github.repository }}/dlsps_helm-charts

    - name: Clean up
      if: always()
      run: |
        rm -rf edge-ai-libraries-repo

    